run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - govet
    - staticcheck
    - unused
    - errcheck
    - revive

issues:
  exclude:
    - "internal/handlers/product.go"
    - "internal/handlers/status.go"
    - "models/storage.go"
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0